name: Deploy to Prod S3

on:
   push:
    branches:
      - main
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Use Node.js 18 LTS
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Build React App
        run: npm install env-cmd --save && npm ci && npm run build
      - name: Deploy app build to S3 bucket
        run: aws s3 sync ./dist/ ${{ secrets.AWS_S3_LOCATION }} --delete
